"""add applications and status history

Revision ID: 5eced8124917
Revises: b0eb60dcce1c
Create Date: 2026-08-09 14:40:41.021437

Hand-adjusted from the autogenerated version. Alembic declared the
`application_status` enum inline in both create_table() calls, which emits
CREATE TYPE twice and fails on the second. The enum types are now created once
up front with checkfirst=True, referenced with create_type=False, and dropped
in downgrade() — without that, a downgrade leaves the types behind and the next
upgrade fails.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5eced8124917"
down_revision: str | None = "b0eb60dcce1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPLICATION_STATUS_VALUES = (
    "wishlist",
    "applied",
    "assessment",
    "phone_screen",
    "technical_interview",
    "hr_interview",
    "final_interview",
    "offer",
    "accepted",
    "rejected",
    "withdrawn",
    "on_hold",
)

application_status = postgresql.ENUM(
    *APPLICATION_STATUS_VALUES, name="application_status", create_type=False
)
work_mode = postgresql.ENUM(
    "onsite", "hybrid", "remote", name="work_mode", create_type=False
)
employment_type = postgresql.ENUM(
    "full_time",
    "part_time",
    "contract",
    "internship",
    name="employment_type",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    application_status.create(bind, checkfirst=True)
    work_mode.create(bind, checkfirst=True)
    employment_type.create(bind, checkfirst=True)

    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("company_website", sa.Text(), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=False),
        sa.Column("job_description", sa.Text(), nullable=True),
        sa.Column("job_url", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("work_mode", work_mode, nullable=True),
        sa.Column("employment_type", employment_type, nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=False),
        sa.Column("status", application_status, nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=True),
        sa.Column("date_posted", sa.Date(), nullable=True),
        sa.Column("date_applied", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name="ck_applications_salary_range",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_applications_user_created", "applications", ["user_id", "created_at"]
    )
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"])
    op.create_index(
        "ix_applications_user_position",
        "applications",
        ["user_id", "status", "position"],
    )
    op.create_index(
        "ix_applications_user_status", "applications", ["user_id", "status"]
    )

    op.create_table(
        "application_status_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("from_status", application_status, nullable=True),
        sa.Column("to_status", application_status, nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_status_history_application_id"),
        "application_status_history",
        ["application_id"],
    )
    op.create_index(
        op.f("ix_application_status_history_changed_at"),
        "application_status_history",
        ["changed_at"],
    )
    op.create_index(
        op.f("ix_application_status_history_user_id"),
        "application_status_history",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_application_status_history_user_id"),
        table_name="application_status_history",
    )
    op.drop_index(
        op.f("ix_application_status_history_changed_at"),
        table_name="application_status_history",
    )
    op.drop_index(
        op.f("ix_application_status_history_application_id"),
        table_name="application_status_history",
    )
    op.drop_table("application_status_history")

    op.drop_index("ix_applications_user_status", table_name="applications")
    op.drop_index("ix_applications_user_position", table_name="applications")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index("ix_applications_user_created", table_name="applications")
    op.drop_table("applications")

    bind = op.get_bind()
    employment_type.drop(bind, checkfirst=True)
    work_mode.drop(bind, checkfirst=True)
    application_status.drop(bind, checkfirst=True)
