/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database health
         * @description Runs a real `SELECT 1` rather than reporting a hardcoded value.
         *
         *     Returns 503 when the database is unreachable so uptime monitors and
         *     container orchestrators see the failure.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password reset link
         * @description Always 204, whether or not the address has an account.
         *
         *     Anything else — a 404, a different message, even a noticeably faster
         *     response — turns this into a way to ask whether a given person has an
         *     account here, which login and registration both refuse to answer.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password using a reset link
         * @description Deliberately does not sign the user in.
         *
         *     A link from an email is weaker evidence than a password, and the reset page
         *     is the one place a stale link is most likely to be opened by the wrong
         *     person. Sending them to the login page to use the password they just chose
         *     costs one form and keeps sessions coming from one place.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh cookie for a new access token */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete the account
         * @description Irreversible, and takes everything with it.
         *
         *     Every table cascades from `users`, including the stored file bytes, so one
         *     delete removes the applications, resumes, interviews and generated answers
         *     too. Nothing is retained.
         */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /**
         * Update name and profile
         * @description One endpoint for the name and the profile fields, because on screen they
         *     are one form and a half-saved form is worse than a slow one.
         */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the profile picture
         * @description Whatever arrives is decoded and re-encoded to a 256px WebP.
         *
         *     That strips EXIF, which on a phone photo carries the coordinates it was
         *     taken at, and it is the only real check that the file is an image rather
         *     than something claiming to be one.
         */
        put: operations["set_avatar_api_v1_users_me_avatar_put"];
        post?: never;
        /** Go back to initials */
        delete: operations["clear_avatar_api_v1_users_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password
         * @description Asks for the current password as well as a valid session — otherwise an
         *     unattended laptop is a way to take the account permanently.
         */
        post: operations["change_password_api_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create an application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applications by stage
         * @description One query, not one per column. Returns every status; the frontend
         *     decides which get columns and which collapse.
         */
        get: operations["get_board_api_v1_applications_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources used so far
         * @description Feeds the source filter without needing a fixed enum.
         */
        get: operations["list_sources_api_v1_applications_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete an application */
        delete: operations["delete_application_api_v1_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update an application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move to another stage
         * @description Separate from PATCH /{id} so every stage change is written to history.
         */
        patch: operations["change_status_api_v1_applications__application_id__status_patch"];
        trace?: never;
    };
    "/api/v1/resumes/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upload limits
         * @description Lets the client reject a file before sending it rather than after.
         *
         *     Declared above /{resume_id} — a literal path registered after a parameterised
         *     one of the same shape is never reached.
         *
         *     Auth is optional rather than required. The file rules are the same for
         *     everyone, and demanding a token to read them would turn a public endpoint
         *     private — breaking every existing caller to add a field. Signed in, the
         *     answer also includes what this account has used.
         */
        get: operations["get_upload_limits_api_v1_resumes_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resumes
         * @description Current version of each resume. Older ones come from /{id}/versions.
         */
        get: operations["list_resumes_api_v1_resumes_get"];
        put?: never;
        /**
         * Upload a resume
         * @description Pass replaces_id to add a version to an existing resume rather than
         *     creating a new one.
         */
        post: operations["upload_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one resume */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete a resume version */
        delete: operations["delete_resume_api_v1_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        /** Update resume details */
        patch: operations["update_resume_api_v1_resumes__resume_id__patch"];
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history */
        get: operations["list_versions_api_v1_resumes__resume_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extracted text
         * @description Separate from the detail view because the text is large and most views
         *     never show it.
         */
        get: operations["get_resume_text_api_v1_resumes__resume_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the file */
        get: operations["download_resume_api_v1_resumes__resume_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How many applications use this
         * @description Shown before deleting, so the consequence is visible first.
         */
        get: operations["get_resume_usage_api_v1_resumes__resume_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/set-current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make this the current version */
        post: operations["set_current_version_api_v1_resumes__resume_id__set_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interviews coming up
         * @description Declared above /{interview_id} so the literal path is reachable.
         */
        get: operations["list_upcoming_api_v1_interviews_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Things needing attention
         * @description Derived from interviews and application dates on each request — there is
         *     no reminders table and nothing to keep in sync.
         */
        get: operations["list_reminders_api_v1_interviews_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interviews for one application */
        get: operations["list_for_application_api_v1_interviews_get"];
        put?: never;
        /** Schedule an interview */
        post: operations["create_interview_api_v1_interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one interview */
        get: operations["get_interview_api_v1_interviews__interview_id__get"];
        put?: never;
        post?: never;
        /** Delete an interview */
        delete: operations["delete_interview_api_v1_interviews__interview_id__delete"];
        options?: never;
        head?: never;
        /** Update an interview */
        patch: operations["update_interview_api_v1_interviews__interview_id__patch"];
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is AI available
         * @description Lets the UI explain why AI is unavailable instead of failing on click.
         */
        get: operations["get_status_api_v1_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything generated for an application */
        get: operations["list_outputs_api_v1_ai_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/applications/{application_id}/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate, or return what was generated before
         * @description Cached by default. Generations cost seconds and quota, so repeat views
         *     reuse the stored answer unless the inputs changed or force is set.
         */
        post: operations["generate_api_v1_ai_applications__application_id___task__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job search statistics
         * @description Everything the analytics page shows, in one request.
         *
         *     One endpoint rather than several: the page draws all of it at once, and
         *     six round trips to a database that sleeps when idle would mean six cold
         *     starts instead of one.
         */
        get: operations["summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIOutputList */
        AIOutputList: {
            /** Items */
            items: components["schemas"]["AIOutputResponse"][];
        };
        /**
         * AIOutputResponse
         * @description One cached generation.
         *
         *     The result is carried in a field typed for its task rather than an untyped
         *     blob. The database stores JSON, but the API describes exactly what each task
         *     produces, so the client gets real types instead of casting a dictionary.
         *
         *     `stale` means the job description or resume changed after this was written,
         *     so it describes text that no longer exists. Shown rather than deleted — an
         *     old answer with a warning beats no answer.
         */
        AIOutputResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            task: components["schemas"]["AITask"];
            analysis?: components["schemas"]["JDAnalysis"] | null;
            match?: components["schemas"]["ResumeMatch"] | null;
            prep?: components["schemas"]["InterviewPrep"] | null;
            /** Text */
            text?: string | null;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /**
         * AIStatus
         * @description Whether AI is usable, so the UI can explain itself instead of failing.
         */
        AIStatus: {
            /** Enabled */
            enabled: boolean;
            /** Provider */
            provider: string;
            /** Detail */
            detail: string;
        };
        /**
         * AITask
         * @enum {string}
         */
        AITask: "jd_analysis" | "resume_match" | "cover_letter" | "interview_questions";
        /**
         * AccountDelete
         * @description Deleting takes the password as well as the session.
         *
         *     It is irreversible and it takes everything, so an unattended laptop should
         *     not be enough on its own.
         */
        AccountDelete: {
            /** Password */
            password: string;
        };
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Min Sample */
            min_sample: number;
            /** Has Enough Data */
            has_enough_data: boolean;
            totals: components["schemas"]["Totals"];
            /** Funnel */
            funnel: components["schemas"]["FunnelStep"][];
            /** Statuses */
            statuses: components["schemas"]["StatusCount"][];
            /** Stage Durations */
            stage_durations: components["schemas"]["StageDuration"][];
            /** Sources */
            sources: components["schemas"]["SourceStat"][];
            /** Volume */
            volume: components["schemas"]["VolumePoint"][];
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title: string;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /**
             * Salary Currency
             * @default INR
             */
            salary_currency: string;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** @default wishlist */
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationDetailResponse
         * @description Detail view adds the journey. Excluded from list responses because it
         *     would mean N extra queries for data the list never shows.
         */
        ApplicationDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Status History
             * @default []
             */
            status_history: components["schemas"]["StatusHistoryEntry"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationStatus
         * @description Not a state machine — real job searches skip stages, go backwards and
         *     revive dead applications. Any transition is allowed; history records it.
         * @enum {string}
         */
        ApplicationStatus: "wishlist" | "applied" | "assessment" | "phone_screen" | "technical_interview" | "hr_interview" | "final_interview" | "offer" | "accepted" | "rejected" | "withdrawn" | "on_hold";
        /** ApplicationStatusUpdate */
        ApplicationStatusUpdate: {
            status: components["schemas"]["ApplicationStatus"];
            /** Position */
            position?: number | null;
        };
        /**
         * ApplicationUpdate
         * @description All fields optional — PATCH semantics.
         *
         *     Status is deliberately absent: it goes through PATCH /{id}/status so every
         *     change is recorded in the history table. Allowing it here would let a
         *     generic update silently bypass that.
         */
        ApplicationUpdate: {
            /** Company Name */
            company_name?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** Position */
            position?: number | null;
        };
        /**
         * AuthResponse
         * @description Returned by register and login: the user plus their access token.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token: components["schemas"]["TokenResponse"];
        };
        /** BoardColumn */
        BoardColumn: {
            status: components["schemas"]["ApplicationStatus"];
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
        };
        /** BoardResponse */
        BoardResponse: {
            /** Columns */
            columns: components["schemas"]["BoardColumn"][];
            /** Total */
            total: number;
        };
        /** Body_set_avatar_api_v1_users_me_avatar_put */
        Body_set_avatar_api_v1_users_me_avatar_put: {
            /** File */
            file: string;
        };
        /** Body_upload_resume_api_v1_resumes_post */
        Body_upload_resume_api_v1_resumes_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
            /** Replaces Id */
            replaces_id?: string | null;
        };
        /**
         * CareerLevel
         * @description `str` mixin so Pydantic serialises the value, not `CareerLevel.STUDENT`.
         * @enum {string}
         */
        CareerLevel: "student" | "entry" | "mid" | "senior" | "lead";
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /**
             * Latency Ms
             * @description Round-trip time of a real SELECT 1
             */
            latency_ms?: number | null;
            /**
             * Error
             * @description Failure reason; omitted when healthy
             */
            error?: string | null;
        };
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship";
        /**
         * ExtractionStatus
         * @description Outcome of pulling text out of an uploaded file.
         *
         *     EMPTY is separate from FAILED on purpose: a scanned resume parses fine and
         *     yields nothing, and telling someone their file is unreadable is more useful
         *     than showing a blank page.
         * @enum {string}
         */
        ExtractionStatus: "pending" | "ok" | "empty" | "failed";
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * FunnelStep
         * @description One rung of the pipeline, counted as "ever reached, not still here".
         *
         *     An application that was rejected after a final round still counts towards
         *     every earlier step — otherwise the funnel would only describe applications
         *     that are currently in flight, which is the least interesting group.
         */
        FunnelStep: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Rate */
            rate: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description "ok" or "degraded"
             */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** InterviewCreate */
        InterviewCreate: {
            round: components["schemas"]["InterviewRound"];
            mode?: components["schemas"]["InterviewMode"] | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Location */
            location?: string | null;
            /** Interviewer */
            interviewer?: string | null;
            /** Notes */
            notes?: string | null;
            /** Feedback */
            feedback?: string | null;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            /** @default pending */
            outcome: components["schemas"]["InterviewOutcome"];
        };
        /**
         * InterviewMode
         * @enum {string}
         */
        InterviewMode: "onsite" | "video" | "phone";
        /**
         * InterviewOutcome
         * @description PENDING covers both "not happened yet" and "happened, still waiting" —
         *     the scheduled time tells those apart without a second field.
         * @enum {string}
         */
        InterviewOutcome: "pending" | "passed" | "failed" | "cancelled";
        /** InterviewPrep */
        InterviewPrep: {
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["InterviewQuestion"][];
            /**
             * Questions To Ask
             * @default []
             */
            questions_to_ask: string[];
        };
        /** InterviewQuestion */
        InterviewQuestion: {
            /** Question */
            question: string;
            /**
             * Category
             * @default role
             */
            category: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Hint
             * @default
             */
            hint: string;
        };
        /** InterviewResponse */
        InterviewResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            round: components["schemas"]["InterviewRound"];
            mode: components["schemas"]["InterviewMode"] | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Location */
            location: string | null;
            /** Interviewer */
            interviewer: string | null;
            /** Notes */
            notes: string | null;
            /** Feedback */
            feedback: string | null;
            outcome: components["schemas"]["InterviewOutcome"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InterviewRound
         * @description Finer grained than ApplicationStatus on purpose.
         *
         *     An application sits in one stage; a stage can contain several interviews,
         *     and "which round was that" is a different question from "where is this
         *     application".
         * @enum {string}
         */
        InterviewRound: "phone_screen" | "technical" | "take_home" | "system_design" | "hr" | "managerial" | "final" | "other";
        /**
         * InterviewUpdate
         * @description PATCH semantics. The application it belongs to is deliberately absent —
         *     moving an interview between applications would rewrite history.
         */
        InterviewUpdate: {
            round?: components["schemas"]["InterviewRound"] | null;
            mode?: components["schemas"]["InterviewMode"] | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Location */
            location?: string | null;
            /** Interviewer */
            interviewer?: string | null;
            /** Notes */
            notes?: string | null;
            /** Feedback */
            feedback?: string | null;
            outcome?: components["schemas"]["InterviewOutcome"] | null;
        };
        /**
         * InterviewWithApplication
         * @description For lists that aren't already inside one application, where "Acme —
         *     Backend Engineer" is the only thing that makes a row meaningful.
         */
        InterviewWithApplication: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            round: components["schemas"]["InterviewRound"];
            mode: components["schemas"]["InterviewMode"] | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Location */
            location: string | null;
            /** Interviewer */
            interviewer: string | null;
            /** Notes */
            notes: string | null;
            /** Feedback */
            feedback: string | null;
            outcome: components["schemas"]["InterviewOutcome"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title: string;
            application_status: components["schemas"]["ApplicationStatus"];
        };
        /** JDAnalysis */
        JDAnalysis: {
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Seniority
             * @default unclear
             */
            seniority: string;
            /**
             * Must Have Skills
             * @default []
             */
            must_have_skills: string[];
            /**
             * Nice To Have Skills
             * @default []
             */
            nice_to_have_skills: string[];
            /**
             * Responsibilities
             * @default []
             */
            responsibilities: string[];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Watch Outs
             * @default []
             */
            watch_outs: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[ApplicationResponse] */
        Page_ApplicationResponse_: {
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Timezone */
            timezone: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            career_level?: components["schemas"]["CareerLevel"] | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * ProfileUpdate
         * @description PATCH semantics: only what was sent is changed.
         *
         *     Email is deliberately absent. Changing it needs a verify-the-new-address
         *     flow and somewhere to send mail from, and accepting a new address without
         *     proving it is reachable would lock people out of their own accounts.
         */
        ProfileUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            /** Timezone */
            timezone?: string | null;
            career_level?: components["schemas"]["CareerLevel"] | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Summary */
            summary?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters
             */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Timezone
             * @description IANA timezone from the browser, e.g. Asia/Kolkata
             */
            timezone?: string | null;
        };
        /**
         * Reminder
         * @description Worked out from the data on each request rather than stored.
         *
         *     A reminders table would need a scheduler to fill it and would go stale the
         *     moment an interview moved; derived ones cannot disagree with the data.
         */
        Reminder: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "interview_upcoming" | "interview_needs_outcome" | "application_stale";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning";
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            /** Interview Id */
            interview_id?: string | null;
            /**
             * Occurs At
             * Format: date-time
             */
            occurs_at: string;
        };
        /** ReminderList */
        ReminderList: {
            /** Items */
            items: components["schemas"]["Reminder"][];
            /** Total */
            total: number;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Token
             * @description From the link in the reset email
             */
            token: string;
            /**
             * Password
             * @description The new password, at least 8 characters
             */
            password: string;
        };
        /** ResumeDetailResponse */
        ResumeDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Extracted Text */
            extracted_text: string | null;
            /**
             * Versions
             * @default []
             */
            versions: components["schemas"]["ResumeResponse"][];
        };
        /** ResumeMatch */
        ResumeMatch: {
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Verdict
             * @default
             */
            verdict: string;
            /**
             * Matched Skills
             * @default []
             */
            matched_skills: string[];
            /**
             * Missing Skills
             * @default []
             */
            missing_skills: string[];
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
        };
        /**
         * ResumeResponse
         * @description Deliberately without extracted_text — it runs to tens of thousands of
         *     characters and no list view shows it.
         */
        ResumeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResumeTextResponse */
        ResumeTextResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extracted Text */
            extracted_text: string | null;
            /** Extraction Error */
            extraction_error: string | null;
        };
        /**
         * ResumeUpdate
         * @description Only the metadata is editable. Replacing the file means a new version.
         */
        ResumeUpdate: {
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ResumeUploadResponse
         * @description The stored resume, plus anything the user should know about it.
         *
         *     duplicate_of is a warning rather than a rejection — uploading the same file
         *     under two titles is a reasonable thing to do, so the choice stays with the
         *     user.
         */
        ResumeUploadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Duplicate Of Id */
            duplicate_of_id?: string | null;
            /** Duplicate Of Title */
            duplicate_of_title?: string | null;
        };
        /** ResumeUsageResponse */
        ResumeUsageResponse: {
            /** Application Count */
            application_count: number;
        };
        /**
         * SourceStat
         * @description Per job board / referral / careers page.
         *
         *     Sources are grouped exactly as typed. Folding "LinkedIn" into "linkedin"
         *     means guessing, and a wrong guess quietly merges two real answers.
         */
        SourceStat: {
            /** Source */
            source: string | null;
            /** Total */
            total: number;
            /** Sent */
            sent: number;
            /** Interviews */
            interviews: number;
            /** Offers */
            offers: number;
            /** Interview Rate */
            interview_rate: number | null;
        };
        /**
         * StageDuration
         * @description How long applications sit in a stage before moving on.
         *
         *     Only completed stays count. An application still sitting in a stage has no
         *     end date, and treating "so far" as "took" would drag every average down.
         */
        StageDuration: {
            status: components["schemas"]["ApplicationStatus"];
            /** Average Days */
            average_days: number;
            /** Median Days */
            median_days: number;
            /** Moves */
            moves: number;
        };
        /**
         * StatusCount
         * @description Where things stand right now. No label — the client already owns the
         *     wording and the colour for each status.
         */
        StatusCount: {
            status: components["schemas"]["ApplicationStatus"];
            /** Count */
            count: number;
        };
        /** StatusHistoryEntry */
        StatusHistoryEntry: {
            from_status: components["schemas"]["ApplicationStatus"] | null;
            to_status: components["schemas"]["ApplicationStatus"];
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
        };
        /**
         * TokenResponse
         * @description The refresh token is intentionally absent — it is delivered as an
         *     httpOnly cookie so JavaScript can never read it.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
        };
        /**
         * Totals
         * @description The headline numbers, and the rates that only appear once earned.
         */
        Totals: {
            /** Applications */
            applications: number;
            /** Active */
            active: number;
            /** Closed */
            closed: number;
            /** Applied */
            applied: number;
            /** Interviews Scheduled */
            interviews_scheduled: number;
            /** Offers */
            offers: number;
            /** Response Rate */
            response_rate: number | null;
            /** Interview Rate */
            interview_rate: number | null;
            /** Offer Rate */
            offer_rate: number | null;
            /** Median Days To Response */
            median_days_to_response: number | null;
            /** Response Samples */
            response_samples: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            profile?: components["schemas"]["ProfileResponse"] | null;
            /** Avatar */
            avatar?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolumePoint
         * @description One week of activity.
         */
        VolumePoint: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Created */
            created: number;
            /** Moved */
            moved: number;
        };
        /**
         * WorkMode
         * @enum {string}
         */
        WorkMode: "onsite" | "hybrid" | "remote";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                applyflow_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_avatar_api_v1_users_me_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_avatar_api_v1_users_me_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_avatar_api_v1_users_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    change_password_api_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                search?: string | null;
                source?: string | null;
                work_mode?: components["schemas"]["WorkMode"] | null;
                sort_by?: "created_at" | "updated_at" | "date_applied" | "company_name" | "job_title";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_api_v1_applications_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
        };
    };
    list_sources_api_v1_applications_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_applications__application_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_limits_api_v1_resumes_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_resumes_api_v1_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
        };
    };
    upload_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_v1_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_api_v1_resumes__resume_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_resumes__resume_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_text_api_v1_resumes__resume_id__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_resume_api_v1_resumes__resume_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_usage_api_v1_resumes__resume_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_current_version_api_v1_resumes__resume_id__set_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upcoming_api_v1_interviews_upcoming_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewWithApplication"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reminders_api_v1_interviews_reminders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderList"];
                };
            };
        };
    };
    list_for_application_api_v1_interviews_get: {
        parameters: {
            query: {
                application_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_api_v1_interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_api_v1_interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interview_api_v1_interviews__interview_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interview_api_v1_interviews__interview_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIStatus"];
                };
            };
        };
    };
    list_outputs_api_v1_ai_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIOutputList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_ai_applications__application_id___task__post: {
        parameters: {
            query?: {
                /** @description Regenerate even if cached */
                force?: boolean;
            };
            header?: never;
            path: {
                application_id: string;
                task: components["schemas"]["AITask"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIOutputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
}
