/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database health
         * @description Runs a real `SELECT 1` rather than reporting a hardcoded value.
         *
         *     Returns 503 when the database is unreachable so uptime monitors and
         *     container orchestrators see the failure.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh cookie for a new access token */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create an application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applications by stage
         * @description One query, not one per column. Returns every status; the frontend
         *     decides which get columns and which collapse.
         */
        get: operations["get_board_api_v1_applications_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources used so far
         * @description Feeds the source filter without needing a fixed enum.
         */
        get: operations["list_sources_api_v1_applications_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete an application */
        delete: operations["delete_application_api_v1_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update an application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move to another stage
         * @description Separate from PATCH /{id} so every stage change is written to history.
         */
        patch: operations["change_status_api_v1_applications__application_id__status_patch"];
        trace?: never;
    };
    "/api/v1/resumes/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upload limits
         * @description Lets the client reject a file before sending it rather than after.
         *
         *     Declared above /{resume_id} — a literal path registered after a parameterised
         *     one of the same shape is never reached.
         */
        get: operations["get_upload_limits_api_v1_resumes_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resumes
         * @description Current version of each resume. Older ones come from /{id}/versions.
         */
        get: operations["list_resumes_api_v1_resumes_get"];
        put?: never;
        /**
         * Upload a resume
         * @description Pass replaces_id to add a version to an existing resume rather than
         *     creating a new one.
         */
        post: operations["upload_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one resume */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete a resume version */
        delete: operations["delete_resume_api_v1_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        /** Update resume details */
        patch: operations["update_resume_api_v1_resumes__resume_id__patch"];
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history */
        get: operations["list_versions_api_v1_resumes__resume_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extracted text
         * @description Separate from the detail view because the text is large and most views
         *     never show it.
         */
        get: operations["get_resume_text_api_v1_resumes__resume_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the file */
        get: operations["download_resume_api_v1_resumes__resume_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How many applications use this
         * @description Shown before deleting, so the consequence is visible first.
         */
        get: operations["get_resume_usage_api_v1_resumes__resume_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/set-current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make this the current version */
        post: operations["set_current_version_api_v1_resumes__resume_id__set_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title: string;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /**
             * Salary Currency
             * @default INR
             */
            salary_currency: string;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** @default wishlist */
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationDetailResponse
         * @description Detail view adds the journey. Excluded from list responses because it
         *     would mean N extra queries for data the list never shows.
         */
        ApplicationDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Status History
             * @default []
             */
            status_history: components["schemas"]["StatusHistoryEntry"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationStatus
         * @description Not a state machine — real job searches skip stages, go backwards and
         *     revive dead applications. Any transition is allowed; history records it.
         * @enum {string}
         */
        ApplicationStatus: "wishlist" | "applied" | "assessment" | "phone_screen" | "technical_interview" | "hr_interview" | "final_interview" | "offer" | "accepted" | "rejected" | "withdrawn" | "on_hold";
        /** ApplicationStatusUpdate */
        ApplicationStatusUpdate: {
            status: components["schemas"]["ApplicationStatus"];
            /** Position */
            position?: number | null;
        };
        /**
         * ApplicationUpdate
         * @description All fields optional — PATCH semantics.
         *
         *     Status is deliberately absent: it goes through PATCH /{id}/status so every
         *     change is recorded in the history table. Allowing it here would let a
         *     generic update silently bypass that.
         */
        ApplicationUpdate: {
            /** Company Name */
            company_name?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** Position */
            position?: number | null;
        };
        /**
         * AuthResponse
         * @description Returned by register and login: the user plus their access token.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token: components["schemas"]["TokenResponse"];
        };
        /** BoardColumn */
        BoardColumn: {
            status: components["schemas"]["ApplicationStatus"];
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
        };
        /** BoardResponse */
        BoardResponse: {
            /** Columns */
            columns: components["schemas"]["BoardColumn"][];
            /** Total */
            total: number;
        };
        /** Body_upload_resume_api_v1_resumes_post */
        Body_upload_resume_api_v1_resumes_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
            /** Replaces Id */
            replaces_id?: string | null;
        };
        /**
         * CareerLevel
         * @description `str` mixin so Pydantic serialises the value, not `CareerLevel.STUDENT`.
         * @enum {string}
         */
        CareerLevel: "student" | "entry" | "mid" | "senior" | "lead";
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /**
             * Latency Ms
             * @description Round-trip time of a real SELECT 1
             */
            latency_ms?: number | null;
            /**
             * Error
             * @description Failure reason; omitted when healthy
             */
            error?: string | null;
        };
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship";
        /**
         * ExtractionStatus
         * @description Outcome of pulling text out of an uploaded file.
         *
         *     EMPTY is separate from FAILED on purpose: a scanned resume parses fine and
         *     yields nothing, and telling someone their file is unreadable is more useful
         *     than showing a blank page.
         * @enum {string}
         */
        ExtractionStatus: "pending" | "ok" | "empty" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description "ok" or "degraded"
             */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[ApplicationResponse] */
        Page_ApplicationResponse_: {
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Timezone */
            timezone: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            career_level?: components["schemas"]["CareerLevel"] | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Summary */
            summary?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters
             */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Timezone
             * @description IANA timezone from the browser, e.g. Asia/Kolkata
             */
            timezone?: string | null;
        };
        /** ResumeDetailResponse */
        ResumeDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Extracted Text */
            extracted_text: string | null;
            /**
             * Versions
             * @default []
             */
            versions: components["schemas"]["ResumeResponse"][];
        };
        /**
         * ResumeResponse
         * @description Deliberately without extracted_text — it runs to tens of thousands of
         *     characters and no list view shows it.
         */
        ResumeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResumeTextResponse */
        ResumeTextResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extracted Text */
            extracted_text: string | null;
            /** Extraction Error */
            extraction_error: string | null;
        };
        /**
         * ResumeUpdate
         * @description Only the metadata is editable. Replacing the file means a new version.
         */
        ResumeUpdate: {
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ResumeUploadResponse
         * @description The stored resume, plus anything the user should know about it.
         *
         *     duplicate_of is a warning rather than a rejection — uploading the same file
         *     under two titles is a reasonable thing to do, so the choice stays with the
         *     user.
         */
        ResumeUploadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Version */
            version: number;
            /** Is Current */
            is_current: boolean;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Error */
            extraction_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Duplicate Of Id */
            duplicate_of_id?: string | null;
            /** Duplicate Of Title */
            duplicate_of_title?: string | null;
        };
        /** ResumeUsageResponse */
        ResumeUsageResponse: {
            /** Application Count */
            application_count: number;
        };
        /** StatusHistoryEntry */
        StatusHistoryEntry: {
            from_status: components["schemas"]["ApplicationStatus"] | null;
            to_status: components["schemas"]["ApplicationStatus"];
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
        };
        /**
         * TokenResponse
         * @description The refresh token is intentionally absent — it is delivered as an
         *     httpOnly cookie so JavaScript can never read it.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            profile?: components["schemas"]["ProfileResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkMode
         * @enum {string}
         */
        WorkMode: "onsite" | "hybrid" | "remote";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                applyflow_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                search?: string | null;
                source?: string | null;
                work_mode?: components["schemas"]["WorkMode"] | null;
                sort_by?: "created_at" | "updated_at" | "date_applied" | "company_name" | "job_title";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_api_v1_applications_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
        };
    };
    list_sources_api_v1_applications_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_applications__application_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_limits_api_v1_resumes_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_resumes_api_v1_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
        };
    };
    upload_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_v1_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_api_v1_resumes__resume_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_resumes__resume_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_text_api_v1_resumes__resume_id__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_resume_api_v1_resumes__resume_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_usage_api_v1_resumes__resume_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_current_version_api_v1_resumes__resume_id__set_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
