/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database health
         * @description Runs a real `SELECT 1` rather than reporting a hardcoded value.
         *
         *     Returns 503 when the database is unreachable so uptime monitors and
         *     container orchestrators see the failure.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh cookie for a new access token */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create an application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applications by stage
         * @description Grouped in one query rather than one request per column.
         *
         *     Every status is returned, including terminal ones — the frontend decides
         *     which to show as columns and which to collapse.
         */
        get: operations["get_board_api_v1_applications_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources used so far
         * @description Powers the source filter dropdown without a fixed enum.
         */
        get: operations["list_sources_api_v1_applications_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete an application */
        delete: operations["delete_application_api_v1_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update an application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move to another stage
         * @description Separate from PATCH /{id} so every stage change is written to history.
         */
        patch: operations["change_status_api_v1_applications__application_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title: string;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /**
             * Salary Currency
             * @default INR
             */
            salary_currency: string;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** @default wishlist */
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationDetailResponse
         * @description Detail view adds the journey. Excluded from list responses because it
         *     would mean N extra queries for data the list never shows.
         */
        ApplicationDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Status History
             * @default []
             */
            status_history: components["schemas"]["StatusHistoryEntry"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Website */
            company_website: string | null;
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string | null;
            /** Job Url */
            job_url: string | null;
            /** Location */
            location: string | null;
            work_mode: components["schemas"]["WorkMode"] | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Source */
            source: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Date Posted */
            date_posted: string | null;
            /** Date Applied */
            date_applied: string | null;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationStatus
         * @description Where an application currently sits.
         *
         *     Deliberately NOT a state machine: real job searches skip stages, go
         *     backwards, and revive dead applications. Any transition is allowed; the
         *     history table records what actually happened.
         * @enum {string}
         */
        ApplicationStatus: "wishlist" | "applied" | "assessment" | "phone_screen" | "technical_interview" | "hr_interview" | "final_interview" | "offer" | "accepted" | "rejected" | "withdrawn" | "on_hold";
        /** ApplicationStatusUpdate */
        ApplicationStatusUpdate: {
            status: components["schemas"]["ApplicationStatus"];
            /** Position */
            position?: number | null;
        };
        /**
         * ApplicationUpdate
         * @description All fields optional — PATCH semantics.
         *
         *     Status is deliberately absent: it goes through PATCH /{id}/status so every
         *     change is recorded in the history table. Allowing it here would let a
         *     generic update silently bypass that.
         */
        ApplicationUpdate: {
            /** Company Name */
            company_name?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Website */
            company_website?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Location */
            location?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Source */
            source?: string | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Date Posted */
            date_posted?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /** Position */
            position?: number | null;
        };
        /**
         * AuthResponse
         * @description Returned by register and login: the user plus their access token.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token: components["schemas"]["TokenResponse"];
        };
        /** BoardColumn */
        BoardColumn: {
            status: components["schemas"]["ApplicationStatus"];
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
        };
        /** BoardResponse */
        BoardResponse: {
            /** Columns */
            columns: components["schemas"]["BoardColumn"][];
            /** Total */
            total: number;
        };
        /**
         * CareerLevel
         * @description `str` mixin so Pydantic serialises the value, not `CareerLevel.STUDENT`.
         * @enum {string}
         */
        CareerLevel: "student" | "entry" | "mid" | "senior" | "lead";
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /**
             * Latency Ms
             * @description Round-trip time of a real SELECT 1
             */
            latency_ms?: number | null;
            /**
             * Error
             * @description Failure reason; omitted when healthy
             */
            error?: string | null;
        };
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description "ok" or "degraded"
             */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[ApplicationResponse] */
        Page_ApplicationResponse_: {
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Timezone */
            timezone: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            career_level?: components["schemas"]["CareerLevel"] | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Summary */
            summary?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters
             */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Timezone
             * @description IANA timezone from the browser, e.g. Asia/Kolkata
             */
            timezone?: string | null;
        };
        /** StatusHistoryEntry */
        StatusHistoryEntry: {
            from_status: components["schemas"]["ApplicationStatus"] | null;
            to_status: components["schemas"]["ApplicationStatus"];
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
        };
        /**
         * TokenResponse
         * @description The refresh token is intentionally absent — it is delivered as an
         *     httpOnly cookie so JavaScript can never read it.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            profile?: components["schemas"]["ProfileResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkMode
         * @enum {string}
         */
        WorkMode: "onsite" | "hybrid" | "remote";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                applyflow_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                search?: string | null;
                source?: string | null;
                work_mode?: components["schemas"]["WorkMode"] | null;
                sort_by?: "created_at" | "updated_at" | "date_applied" | "company_name" | "job_title";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_api_v1_applications_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
        };
    };
    list_sources_api_v1_applications_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_applications__application_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
