"""File storage.

Everything above this module deals in opaque string keys, so the backend is a
swappable detail. Two exist: the database, and local disk.
"""

import shutil
import uuid
from abc import ABC, abstractmethod
from io import BytesIO
from pathlib import Path
from typing import IO

from sqlalchemy import delete as sql_delete
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.stored_file import StoredFile


class StorageError(Exception):
    """Storage was reachable but the operation failed."""


class FileNotStored(StorageError):
    """No object exists for that key."""


class Storage(ABC):
    @abstractmethod
    def save(self, key: str, source: IO[bytes], *, owner_id: uuid.UUID | None = None) -> None:
        """Write the object. owner_id, where a backend can use it, ties the
        bytes to an account so they can be cleaned up with it."""

    @abstractmethod
    def open(self, key: str) -> IO[bytes]: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def exists(self, key: str) -> bool: ...


class PostgresStorage(Storage):
    """Bytes in the database, in the caller's session.

    Sharing the session is the point: a file and the row describing it commit or
    roll back together, so neither can outlive the other.
    """

    def __init__(self, db: Session) -> None:
        self.db = db

    def save(self, key: str, source: IO[bytes], *, owner_id: uuid.UUID | None = None) -> None:
        content = source.read()
        # Upsert rather than insert: re-saving a key is a replacement, and a
        # retried upload should not fail on the primary key.
        self.db.execute(
            pg_insert(StoredFile)
            .values(key=key, owner_id=owner_id, content=content, size_bytes=len(content))
            .on_conflict_do_update(
                index_elements=[StoredFile.key],
                set_={"content": content, "size_bytes": len(content), "owner_id": owner_id},
            )
        )
        self.db.flush()

    def open(self, key: str) -> IO[bytes]:
        content = self.db.execute(
            select(StoredFile.content).where(StoredFile.key == key)
        ).scalar_one_or_none()

        if content is None:
            raise FileNotStored(key)
        return BytesIO(content)

    def delete(self, key: str) -> None:
        self.db.execute(sql_delete(StoredFile).where(StoredFile.key == key))
        self.db.flush()

    def exists(self, key: str) -> bool:
        return (
            self.db.execute(
                select(StoredFile.key).where(StoredFile.key == key)
            ).scalar_one_or_none()
            is not None
        )


class LocalStorage(Storage):
    """Files under UPLOAD_DIR. Development only — a host with an ephemeral disk
    loses everything written here on the next deploy."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # Keys are generated by us, but resolve and re-check anyway: one day a
        # key will come from a request and this is the line that stops it
        # writing outside the upload directory.
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):
            raise StorageError(f"Refusing to access a path outside storage: {key}")
        return path

    def save(self, key: str, source: IO[bytes], *, owner_id: uuid.UUID | None = None) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("wb") as target:
            shutil.copyfileobj(source, target)

    def open(self, key: str) -> IO[bytes]:
        path = self._path(key)
        try:
            return path.open("rb")
        except FileNotFoundError as exc:
            raise FileNotStored(key) from exc

    def delete(self, key: str) -> None:
        # missing_ok: deleting something already gone is the desired end state,
        # not an error worth surfacing.
        self._path(key).unlink(missing_ok=True)

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()


def build_key(user_id: uuid.UUID, resume_id: uuid.UUID, filename: str) -> str:
    """Namespaced by user, named by resume id.

    The original filename only contributes its extension — user-supplied names
    are not safe as paths, and the real name is kept in the database anyway.
    """
    suffix = Path(filename).suffix.lower()
    if suffix not in {".pdf"}:
        suffix = ".bin"
    return f"resumes/{user_id}/{resume_id}{suffix}"


def build_storage(db: Session) -> Storage:
    if settings.STORAGE_BACKEND == "local":
        return LocalStorage(settings.UPLOAD_DIR)
    return PostgresStorage(db)
